In [5]:
import pandas as pd
from IPython.display import HTML

dataset = pd.read_csv("healthcare-dataset-stroke-data.csv")
HTML(dataset.head(10).to_html(index=False))